// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

Future<void> initializeFirebase() async {}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8Phy0MfIi1QhiRlSevn3BVa1Y8vJl1g',
    appId: '1:653927138262:android:c01105f09e33577e5b1a77',
    messagingSenderId: '653927138262',
    projectId: 'vinemas-nhanta',
    storageBucket: 'vinemas-nhanta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // apiKey: 'AIzaSyC5pFnH8sjfLPeOfGJ8wnQg27aSCkl8RHc',
    // appId: '1:653927138262:ios:1c288eb3089979415b1a77',
    apiKey: 'AIzaSyC5pFnH8sjfLPeOfGJ8wnQg27aSCkl8RHc',
    appId: '1:653927138262:ios:b1b73ad4a3ddc9015b1a77',
    messagingSenderId: '653927138262',
    projectId: 'vinemas-nhanta',
    storageBucket: 'vinemas-nhanta.appspot.com',
    iosBundleId: 'com.nhanta.vinemas',
  );
}
